#!/bin/bash
#plone_images
cp src/gif/16x16/text-html.gif skins/tango_plone_images/document_icon.gif
cp src/gif/16x16/folder.gif skins/tango_plone_images/folder_icon.gif
cp src/gif/32x32/folder.gif skins/tango_plone_images/folder.gif
cp src/gif/16x16/emblem-important.gif skins/tango_plone_images/info_icon.gif
cp src/gif/16x16/next.gif skins/tango_plone_images/linkTransparent.gif
cp src/gif/16x16/mail-forward.gif skins/tango_plone_images/mail_icon.gif
cp src/gif/16x16/document-print.gif skins/tango_plone_images/print_icon.gif
cp src/gif/16x16/system-search.gif skins/tango_plone_images/search_icon.gif
cp src/gif/16x16/folder-saved-search.gif skins/tango_plone_images/topic_icon.gif
cp src/gif/16x16/page-livemarks.gif skins/tango_plone_images/rss.gif
cp src/gif/16x16/x-office-calendar.gif skins/tango_plone_images/event_icon.gif
cp src/gif/16x16/x-office-calendar.gif skins/tango_plone_images/popup_calendar.gif
cp src/gif/16x16/internet-news-reader.gif skins/tango_plone_images/newsitem_icon.gif
cp src/gif/16x16/user.gif skins/tango_plone_images/user.gif
cp src/gif/16x16/group.gif skins/tango_plone_images/group.gif
cp src/gif/16x16/internet-group-chat.gif skins/tango_plone_images/discussionitem_icon.gif
cp src/gif/16x16/view-fullscreen.gif skins/tango_plone_images/fullscreenexpand_icon.gif
cp src/gif/16x16/view-fullscreen-inverted.gif skins/tango_plone_images/fullscreencollapse_icon.gif
cp src/gif/16x16/internet-web-browser.gif skins/tango_plone_images/link_icon.gif
cp src/gif/16x16/document-save.gif skins/tango_plone_images/download_icon.gif
cp src/gif/16x16/edit-copy.gif skins/tango_plone_images/copy_icon.gif
cp src/gif/16x16/edit-cut.gif skins/tango_plone_images/cut_icon.gif
cp src/gif/16x16/edit-delete.gif skins/tango_plone_images/delete_icon.gif
cp src/gif/16x16/edit-paste.gif skins/tango_plone_images/paste_icon.gif
cp src/gif/16x16/preferences-desktop-theme.gif skins/tango_plone_images/skins_icon.gif
cp src/gif/16x16/preferences-system-windows.gif skins/tango_plone_images/navigation_icon.gif
cp src/gif/16x16/text-x-generic-template.gif skins/tango_plone_images/file_icon.gif
cp src/gif/16x16/emblem-favorite.gif skins/tango_plone_images/favorite_icon.gif
cp src/gif/16x16/emblem-favorite.gif skins/tango_plone_images/rtl-favorite_icon.gif
cp src/gif/16x16/image-x-generic.gif skins/tango_plone_images/image_icon.gif
cp src/gif/16x16/preferences-system-windows.gif skins/tango_plone_images/sitemap_icon.gif
cp src/gif/16x16/draw-freehand.gif skins/tango_plone_images/edit.gif
cp src/gif/16x16/draw-freehand.gif skins/tango_plone_images/extedit_icon.gif
cp src/gif/16x16/draw-freehand.gif skins/tango_plone_images/pencil_icon.gif
cp src/gif/extra/defaultUser.gif skins/tango_plone_images/defaultUser.gif